<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
/*	public function findAll(){

		$query = $this->createQueryBuilder('c')
			->select('c')
			->where('c.isActive = 1');

		return $query->getQuery()->getResult();
	}*/
}
