<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FavorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorRepository extends EntityRepository
{
	public function findCandidaturas($usuarioId){
		$query = $this->createQueryBuilder('f')
			->select('f')
		    ->where('f.elegido = :usuarioId')
		    ->setParameter(':usuarioId', $usuarioId);
	    
	    return $query->getQuery()->getResult();
	}

	public function getCantFavoresDeCategoria($categoria){
		$query = $this->createQueryBuilder('f')
			->select('COUNT(f)')
			->innerJoin('f.categoria', 'c')
			->where('c.id = :categoria')
			->setParameter('categoria', $categoria);

			return $query->getQuery()->getSingleScalarResult();
	}
}
