# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        usuario:
            entity: { class: AppBundle\Entity\Usuario, property: email }

    encoders:
        AppBundle\Entity\Usuario: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: usuario_logout
                target: homepage
            remember_me:
                secret: wam1551n6pl4y3rsd
                lifetime: 604800
                always_remember_me: true
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
       - { path: ^/login/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/usuario/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/*, roles: [ROLE_USER, ROLE_ADMIN] }
    

